/**
 * astra dev
 * API interface for \'astra dev\'
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DevstateExecCommandPostRequest { 
    /**
     * Name of the command
     */
    name?: string;
    component?: string;
    commandLine?: string;
    workingDir?: string;
    hotReloadCapable?: boolean;
}

